'use strict';

import { Alphabet, PlugBoard, M4 } from '../src/enigmaISimulator/enigma';

/* SOURCE: https://www.bytereef.org/m4-project-first-break.html */
test('M4 FIRST BROKEN MESSAGE', () => {
    expect(
        new M4(
            new PlugBoard(Alphabet.capitalLatin, ['A', 'T'], ['B', 'L'], ['D', 'F'], ['G', 'J'], ['H', 'M'], ['N', 'W'], ['O', 'P'], ['Q', 'Y'], ['R', 'Z'], ['V', 'X']),
            M4.rotorI,
            M4.rotorIV,
            M4.rotorII,
            M4.rotorBeta,
            M4.reflectorB,
            'VAAA',
            'ANJV'
        ).decrypt(
            'NCZWVUSXPNYMINHZXMQXSFWXWLKJAHSHNMCOCCAKUQPMKCSMHKSEINJUSBLKIOSXCKUBHMLLXCSJUSRRDVKOHULXWCCBGVLIYXEOAHXRHKKFVDREWEZLXOBAFGYUJQUKGRTVUKAMEURBVEKSUHHVOYHABCJWMAKLFKLMYFVNRIZRVVRTKOFDANJMOLBGFFLEOPRGTFLVRHOWOPBEKVWMUQFMPWPARMFHAGKXIIBG'
        )
    ).toBe(
        'VONVONJLOOKSJHFFTTTEINSEINSDREIZWOYYQNNSNEUNINHALTXXBEIANGRIFFUNTERWASSERGEDRUECKTYWABOSXLETZTERGEGNERSTANDNULACHTDREINULUHRMARQUANTONJOTANEUNACHTSEYHSDREIYZWOZWONULGRADYACHTSMYSTOSSENACHXEKNSVIERMBFAELLTYNNNNNNOOOVIERYSICHTEINSNULL'
    );
});

/* SOURCE: https://www.bytereef.org/m4-project-second-break.html */
test('M4 SECOND BROKEN MESSAGE', () => {
    expect(
        new M4(
            new PlugBoard(Alphabet.capitalLatin, ['A', 'T'], ['C', 'L'], ['D', 'H'], ['E', 'P'], ['F', 'G'], ['I', 'O'], ['J', 'N'], ['K', 'Q'], ['M', 'U'], ['R', 'X']),
            M4.rotorI,
            M4.rotorIV,
            M4.rotorII,
            M4.rotorBeta,
            M4.reflectorB,
            'VNAA',
            'FSCM'
        ).decrypt(
            'TMKFNWZXFFIIYXUTIHWMDHXIFZEQVKDVMQSWBQNDYOZFTIWMJHXHYRPACZUGRREMVPANWXGTKTHNRLVHKZPGMNMVSECVCKHOINPLHHPVPXKMBHOKCCPDPEVXVVHOZZQBIYIEOUSEZNHJKWHYDAGTXDJDJKJPKCSDSUZTQCXJDVLPAMGQKKSHPHVKSVPCBUWZFIZPFUUP'
        )
    ).toBe(
        'VVVJSCHREEDERJAUFGELEITKURSFUENFFUENFGRADNICHTSGEFUNDENYMARSCAIEREBEFOHLENESQUADRATXSTANRORTMARQUANTONJOTADREINEUNNEUNFUENFXSSSOOOVIERYSEEDREMYEINSNULYYEINSNULBEDECKTYZWOACHTMBSTEIGTYNBBELSICHTEINSSMT'
    );
});

/* SOURCE: https://enigma.hoerenberg.com/index.php?cat=M4%20Project%202006&page=Rasch%20Message */
test('M4 FINAL BROKEN MESSAGE', () => {
    expect(
        new M4(
            new PlugBoard(Alphabet.capitalLatin, ['B', 'Q'], ['C', 'R'], ['D', 'I'], ['E', 'J'], ['K', 'W'], ['M', 'T'], ['O', 'S'], ['P', 'X'], ['U', 'Z'], ['G', 'H']),
            M4.rotorIII,
            M4.rotorI,
            M4.rotorVI,
            M4.rotorBeta,
            M4.reflectorB,
            'GTZZ',
            'LHBN'
        ).decrypt(
            'HCEYZTCSOPUPPZDICQRDLWXXFACTTJMBRDVCJJMMZRPYIKHZAWGLYXWTMJPQUEFSZBOTVRLALZXWVXTSLFFFAUDQFBWRRYAPSBOWJMKLDUYUPFUQDOWVHAHCDWAUARSWTKOFVOYFPUFHVZFDGGPOOVGRMBPXXZCANKMONFHXPCKHJZBUMXJWXKAUODXZUCVCXPFT'
        )
    ).toBe(
        'BOOTKLARXBEIJSCHNOORBETWAZWOSIBENXNOVXSECHSNULCBMXPROVIANTBISZWONULXDEZXBENOETIGEGLMESERYNOCHVIEFKLHRXSTEHEMARQUBRUNOBRUNFZWOFUHFXLAGWWIEJKCHAEFERJXNNTWWWFUNFYEINSFUNFMBSTEIGENDYGUTESIWXDVVVJRASCH'
    );
});
